### ISSUE TITLE
[alea] compilation failure with gcc-7.1

### ISSUE THREAD

**Issue by kleinhenz** [ALPSCore/ALPSCore#486]
alea does not compile with gcc-7.1 on cori due to the following error

```
/global/homes/j/jkleinh/research/libraries/ALPSCore/alea/include/alps/alea/complex_op.hpp:207:28: error: invalid static_cast from type '<unresolved overloaded function type>' to type 'bool (*)(double)'
                            static_cast<bool(*)(T)>(std::isnan));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
