### ISSUE TITLE
Homebrew build on Jenkins fails

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#173]
The build fails with linker error message:

    Undefined symbols for architecture x86_64:
      "boost::archive::basic_text_iprimitive<std::istream>::~basic_text_iprimitive()", referenced from:
          boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::~text_iarchive_impl() in params.cpp.o
      "boost::archive::basic_text_oprimitive<std::ostream>::~basic_text_oprimitive()", referenced from:
          boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::~text_oarchive_impl() in params.cpp.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

I suspect it is the same issue as #161 : an updated Boost is needed.
Andrey (@aeantipov) --- could you please look at it some time?

**Comment by aeantipov** [comment]
Checked it on my mac - works with 1.58.0 
Does the error show up, when linking a library or a test?

**Comment by galexv** [comment]
Boost 1.58.0 is fine, it is 1.59.0 that has the problem (fixed upstream, https://svn.boost.org/trac/boost/ticket/11671; fixed in macports, https://trac.macports.org/ticket/48717).

It shows up when linking `libalps-params.dylib`, and the problem is because of `boost::archive` (i think that once we get rid of boost serialization, the error will go away).

Can we use Boost 1.58.0 for homebrew for now? (Where does it get Boost from?)

**Comment by aeantipov** [comment]
homebrew : alpscore + boost 1.59 works. The patch https://gist.githubusercontent.com/tdsmith/bc76ddea1e2bdb2a3a18/raw/03d125b12a4b03c28ee011a2d6d42a8137061a3b/boost-log.patch is applied when boost is installed.

**Comment by galexv** [comment]
Thanks a lot!

**Comment by aeantipov** [comment]
Looked more into it. The patch I mentioned is not the right one. 
The right patch for the problem seems to be
https://raw.githubusercontent.com/MrKepzie/Natron/workshop/tools/MacOSX/ports/devel/boost/files/patch-serialization-visibility.diff
I will file it to homebrew

**Comment by aeantipov** [comment]
Upon further check this bug is a combination of boost-1.59 + mac os 10.8 (works on >=10.9).
The fix is now incorporated in boost and should be included with its next release.
Until then, the brew build is switched to boost-1.55.
