### ISSUE TITLE
[gf] Test fails to build with clang 3.4.2 

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#598]
Looks like clang 3.4.2 does not like someting in [gf/test/fourier_test.cpp](https://github.com/ALPSCore/ALPSCore/blob/df8d11e3f16603b3c2a49976432f4cc83ff826ea/gf/test/fourier_test.cpp#L194)

```
.../gf/test/fourier_test.cpp:194:3: error: no matching function for call to 'fourier_frequency_to_time'
  fourier_frequency_to_time(g_omega, g_tau);
  ^~~~~~~~~~~~~~~~~~~~~~~~~
.../gf/include/alps/gf/fourier.hpp:83:33: note: candidate template ignored: could not match 'tensor_base<[...], 1, [...]>' against 'tensor_base<[...], 2, [...]>'
  template<class...MESHES> void fourier_frequency_to_time(
```

See the compilation log at
http://pauli.physics.lsa.umich.edu:8080/job/Public_projects/job/ALPSCore/COMPILER=clang_3.4.2,MPI_VERSION=MPI_OFF/25/console

Sergei (@iskakoff), could you please have a look?
